### ISSUE TITLE
Automate font updating

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-font#10]
Once icons are edited or added in bpmn-font, the font in the following projects should be updated automatically:
- bpmn-js
- bpmn-io-demo
- bpmn-io-chrome
- bpmn-io-modeler

This involves: updating the Fontello config.json in the projects, getting the updated font files and copying it to the right places in the project. We should make use of the [Fontello API](https://github.com/fontello/fontello#developers-api) to achieve that.

**Comment by nikku** [comment]
We'll not do this any time soon.
