### ISSUE TITLE
Prefix font CSS selector with bpmn-icon-

### ISSUE THREAD

**Issue by mhariri** [bpmn-io/bpmn-font#12]
In bpmn-embedded.js, line 25:

     [class^="icon-"]:before, [class*=" icon-"]:before {

This attribute collides with many other libraries that use "icon-" prefix, can you make it more specific, eg using "bpmn-icon" prefix?

**Comment by nikku** [comment]
I think the icon prefix is common among icon libraries. You usually won't mix more of them together in an application. 

We are using [fontello](http://fontello.com) to generate custom combined per-application fonts.

If you'd like to use a `bpmn-icon-` prefixed version of the font, simply generate it via the provided [`fontello/config.json`](https://github.com/bpmn-io/bpmn-font/blob/master/fontello/config.json) file. There you'd need to adjust the `css_prefix_text` to suite your needs.

**Comment by nikku** [comment]
We will work on this and prefix the font with `bpmn-icon-` as you suggested. This will give users a better getting started.

**Comment by mhariri** [comment]
great! thanks for the awesome work :)
