### ISSUE TITLE
Release new version on npm

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-font#15]
Seems like the bpmn.io npm account isn't allowed to publish new versions of this library:

__Console error__

![image](https://user-images.githubusercontent.com/9433996/57675721-074e0f80-7623-11e9-84a3-08baf2f6d52f.png)

__npm registry page__

![image](https://user-images.githubusercontent.com/9433996/57675733-1339d180-7623-11e9-9a82-0e4d12fb1ff9.png)

* [x] allow bpmn.io account to publish new versions
* [ ] publish `v0.9.0` with new Group icons

**Comment by philippfromme** [comment]
🙈 🙈 🙈

**Comment by nikku** [comment]
![image](https://user-images.githubusercontent.com/58601/57799240-ee427d00-774e-11e9-8011-f70b7b7167a7.png)

**Comment by pinussilvestrus** [comment]
Closed via release `v0.9.0`
