### ISSUE TITLE
provide intermediate-event-catch-error as -non-interrupting-

### ISSUE THREAD

**Issue by ShawnKleese** [bpmn-io/bpmn-font#17]
Would it be possible to provide the " intermediate-event-catch-error" as " intermediate-event-catch-non-interrupting-error" ?

bpmn-icon-intermediate-event-catch-non-interrupting-message

I think this makes also sense in some usecases

**Comment by pinussilvestrus** [comment]
Why do you think it would make more sense?

**Comment by ShawnKleese** [comment]
After some discussions with my colleagues, we think thats make not really sense.

Sorry
