### ISSUE TITLE
Demo page is unavailable

### ISSUE THREAD

**Issue by ptyin** [bpmn-io/bpmn-font#23]
### Describe the Bug

[demo page](https://cdn.staticaly.com/gh/bpmn-io/bpmn-font/master/dist/demo.html)
The browser raised ERR_SSL_PROTOCOL_ERROR.

**Comment by nikku** [comment]
This is very likely a temporary glitch. We'll monitor the situation.

**Comment by ptyin** [comment]
Thanks, the demo page helps a lot.

**Comment by nikku** [comment]
Actually required explicit fix via https://github.com/bpmn-io/bpmn-font/commit/1a3f97d3ff824be3e2ea29cf5f0da360e7903011. Thanks for reporting.
